exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] sleep 5 && vivaldi # It needs ags to start first
exec-once = [workspace 3 silent] kitty nchat
exec-once = [workspace 3 silent] sleep 5 && line
exec-once = [workspace 3 silent] discord --ozone-platform=wayland # Not silent
exec-once = [workspace 4 silent] obsidian
exec-once = [workspace 4 silent] LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
exec-once = [workspace 10 silent] keepassxc
