exec-once = [workspace 1; suppress_event fullscreen, maximize, activate] kitty
exec-once = [workspace 2; suppress_event fullscreen, maximize, activate] firefox
exec-once = [workspace 3; suppress_event fullscreen, maximize, activate] kitty nchat
exec-once = [workspace 3; suppress_event fullscreen, maximize, activate] line
exec-once = [workspace 3; suppress_event fullscreen, maximize, activate] discord --ozone-platform=wayland # Not silent
exec-once = [workspace 4; suppress_event fullscreen, maximize, activate] obsidian
exec-once = [workspace 4; suppress_event fullscreen, maximize, activate] LD_PRELOAD=/usr/lib/spotify-adblock.so spotify
exec-once = [workspace 10; suppress_event fullscreen, maximize, activate] keepassxc
